apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-server
  labels:
    app: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        image: gcr.io/inspired-brand-324120/worker-server:v4
        env:
        - name: REDIS_HOST
          value: redis
        - name: RABBITMQ_HOST
          value: rabbitmq